class WordEntry {
  final String translation;
  final String level;
  final String partOfSpeech;
  final String definitionEn;
  final String definitionAr;
  final List<String> examples;
  final List<String> synonyms;
  final List<SimilarWord> similar;

  const WordEntry({
    required this.translation,
    required this.level,
    required this.partOfSpeech,
    required this.definitionEn,
    required this.definitionAr,
    required this.examples,
    required this.synonyms,
    required this.similar,
  });
}

class SimilarWord {
  final String word;
  final String translation;
  final String level;
  const SimilarWord(this.word, this.translation, this.level);
}

const wordDataMap = <String, WordEntry>{
  'sustainable': WordEntry(
    translation: 'مستدام',
    level: 'B1',
    partOfSpeech: 'adjective',
    definitionEn: 'Able to be maintained at a certain rate or level over time.',
    definitionAr: 'قادر على الاستمرار بمعدل أو مستوى معين مع مرور الوقت.',
    examples: [
      'We need sustainable energy sources for the future.',
      'The company focuses on sustainable business practices.',
      'Sustainable agriculture is essential for food security.',
    ],
    synonyms: ['maintainable', 'renewable', 'viable', 'green', 'eco-friendly'],
    similar: [
      SimilarWord('renewable', 'متجدد', 'B2'),
      SimilarWord('viable', 'قابل للحياة', 'C1'),
      SimilarWord('eco-friendly', 'صديق للبيئة', 'B1'),
    ],
  ),
  'significant': WordEntry(
    translation: 'مهم / كبير',
    level: 'B1',
    partOfSpeech: 'adjective',
    definitionEn: 'Sufficiently great or important to be worthy of attention.',
    definitionAr: 'كافٍ من حيث الأهمية أو القيمة ليستحق الاهتمام.',
    examples: [
      'The study showed significant results that changed our understanding.',
      'There has been a significant increase in sales this quarter.',
      'Her contribution to the project was truly significant.',
    ],
    synonyms: ['notable', 'remarkable', 'substantial', 'important', 'major'],
    similar: [
      SimilarWord('substantial', 'كبير / جوهري', 'B2'),
      SimilarWord('notable', 'ملحوظ', 'B1'),
      SimilarWord('crucial', 'حاسم', 'B2'),
    ],
  ),
  'breakthrough': WordEntry(
    translation: 'اختراق',
    level: 'C1',
    partOfSpeech: 'noun',
    definitionEn: 'A sudden, dramatic, and important discovery or development.',
    definitionAr: 'اكتشاف أو تطور مفاجئ ومهم.',
    examples: [
      'The scientists made a major breakthrough in cancer research.',
      'This breakthrough could change the world as we know it.',
      'The breakthrough came after years of dedicated research.',
    ],
    synonyms: ['discovery', 'innovation', 'advancement', 'leap', 'revolution'],
    similar: [
      SimilarWord('discovery', 'اكتشاف', 'B1'),
      SimilarWord('innovation', 'ابتكار', 'B2'),
      SimilarWord('advancement', 'تقدم', 'B2'),
    ],
  ),
  'comprehensive': WordEntry(
    translation: 'شامل',
    level: 'B2',
    partOfSpeech: 'adjective',
    definitionEn:
        'Including or dealing with all or nearly all elements or aspects of something.',
    definitionAr: 'يشمل أو يتعامل مع كل أو几乎所有 العناصر أو الجوانب.',
    examples: [
      'We need a comprehensive review of the current system.',
      'The report provides a comprehensive analysis of the situation.',
      'She received comprehensive training before starting the job.',
    ],
    synonyms: ['complete', 'thorough', 'extensive', 'full', 'exhaustive'],
    similar: [
      SimilarWord('thorough', 'دقيق', 'B1'),
      SimilarWord('extensive', 'واسع', 'B2'),
      SimilarWord('complete', 'كامل', 'A2'),
    ],
  ),
  'widespread': WordEntry(
    translation: 'واسع الانتشار',
    level: 'B2',
    partOfSpeech: 'adjective',
    definitionEn: 'Found or distributed over a large area or number of people.',
    definitionAr: 'موجود أو موزع على مساحة كبيرة أو عدد كبير من الناس.',
    examples: [
      'The disease is widespread in rural areas.',
      'There is widespread support for the new policy.',
      'Smartphone usage has become widespread across all age groups.',
    ],
    synonyms: ['extensive', 'broad', 'prevalent', 'common', 'general'],
    similar: [
      SimilarWord('prevalent', 'سائد', 'C1'),
      SimilarWord('extensive', 'واسع', 'B2'),
      SimilarWord('common', 'شائع', 'A2'),
    ],
  ),
  'despite': WordEntry(
    translation: 'بالرغم من',
    level: 'B1',
    partOfSpeech: 'preposition',
    definitionEn: 'Without being affected by; in spite of.',
    definitionAr: 'دون أن يتأثر بـ؛ على الرغم من.',
    examples: [
      'Despite the rain, they continued playing the match.',
      'She succeeded despite many difficulties and obstacles.',
      'Despite his age, he remains very active and energetic.',
    ],
    synonyms: ['notwithstanding', 'regardless of', 'even with', 'in spite of'],
    similar: [
      SimilarWord('although', 'على الرغم من أن', 'B1'),
      SimilarWord('nevertheless', 'مع ذلك', 'B2'),
      SimilarWord('nonetheless', 'على أي حال', 'C1'),
    ],
  ),
  'implement': WordEntry(
    translation: 'ينفذ / يطبق',
    level: 'B1',
    partOfSpeech: 'verb',
    definitionEn: 'To put a decision, plan, or agreement into effect.',
    definitionAr: 'وضع قرار أو خطة أو اتفاق موضع التنفيذ.',
    examples: [
      'The company will implement the new policy next month.',
      'We need to implement changes to improve efficiency.',
      'They implemented a new system for tracking orders.',
    ],
    synonyms: ['execute', 'apply', 'enforce', 'carry out', 'realize'],
    similar: [
      SimilarWord('execute', 'ينفذ', 'B2'),
      SimilarWord('apply', 'يطبق', 'B1'),
      SimilarWord('enforce', 'يفرض', 'C1'),
    ],
  ),
  'consequently': WordEntry(
    translation: 'وبالتالي',
    level: 'B2',
    partOfSpeech: 'adverb',
    definitionEn: 'As a result or effect of something.',
    definitionAr: 'كنتيجة أو أثر لشيء ما.',
    examples: [
      'He was late and consequently missed the bus.',
      'The temperature dropped; consequently, the pipes froze.',
      'She practiced daily and consequently improved dramatically.',
    ],
    synonyms: ['therefore', 'thus', 'hence', 'accordingly', 'as a result'],
    similar: [
      SimilarWord('therefore', 'لذلك', 'B1'),
      SimilarWord('accordingly', 'بناء على ذلك', 'B2'),
      SimilarWord('hence', 'ومن ثم', 'C1'),
    ],
  ),
  'sustainably': WordEntry(
    translation: 'بشكل مستدام',
    level: 'B2',
    partOfSpeech: 'adverb',
    definitionEn:
        'In a way that can be maintained over the long term without harming the environment.',
    definitionAr:
        'بطريقة يمكن الاستمرار بها على المدى الطويل دون الإضرار بالبيئة.',
    examples: [
      'The forest is managed sustainably for future generations.',
      'We must produce energy more sustainably to protect the planet.',
      'The company aims to grow sustainably without compromising values.',
    ],
    synonyms: ['responsibly', 'renewably', 'ecologically', 'greenly'],
    similar: [
      SimilarWord('responsibly', 'بمسؤولية', 'B1'),
      SimilarWord('ecologically', 'بيئياً', 'C1'),
      SimilarWord('renewably', 'بشكل متجدد', 'C1'),
    ],
  ),
  'emerging': WordEntry(
    translation: 'ناشئ',
    level: 'B2',
    partOfSpeech: 'adjective',
    definitionEn: 'Newly developed or just becoming noticeable.',
    definitionAr: 'مُطوَّر حديثاً أو بدأ للتو في الظهور.',
    examples: [
      'Emerging technologies are changing the way we live.',
      'The emerging market shows great potential for growth.',
      'She is an emerging talent in the film industry.',
    ],
    synonyms: ['developing', 'growing', 'rising', 'nascent', 'new'],
    similar: [
      SimilarWord('developing', 'نامٍ', 'B1'),
      SimilarWord('nascent', 'ناشئ', 'C1'),
      SimilarWord('growing', 'متنامٍ', 'B1'),
    ],
  ),
  'secured': WordEntry(
    translation: 'حصل على / ضمن',
    level: 'B1',
    partOfSpeech: 'verb',
    definitionEn: 'Obtained or achieved something, especially with effort.',
    definitionAr: 'حصل على أو حقق شيئاً، خاصةً بجهد.',
    examples: [
      'The team secured their place in the final match.',
      'She secured a job at the company after many interviews.',
      'They secured funding for their research project.',
    ],
    synonyms: ['obtained', 'achieved', 'gained', 'acquired', 'attained'],
    similar: [
      SimilarWord('obtain', 'يحصل على', 'B1'),
      SimilarWord('achieve', 'يحقق', 'B1'),
      SimilarWord('acquire', 'يكتسب', 'B2'),
    ],
  ),
  'remarkable': WordEntry(
    translation: 'رائع / مميز',
    level: 'B2',
    partOfSpeech: 'adjective',
    definitionEn: 'Worthy of attention; striking or extraordinary.',
    definitionAr: 'يستحق الاهتمام؛ لافت أو استثنائي.',
    examples: [
      'He made a remarkable recovery after the accident.',
      'It was a remarkable achievement for such a young athlete.',
      'The view from the mountain was absolutely remarkable.',
    ],
    synonyms: [
      'extraordinary',
      'notable',
      'impressive',
      'striking',
      'exceptional',
    ],
    similar: [
      SimilarWord('extraordinary', 'استثنائي', 'B2'),
      SimilarWord('exceptional', 'استثنائي', 'C1'),
      SimilarWord('striking', 'لافت', 'B2'),
    ],
  ),
  'exceptional': WordEntry(
    translation: 'استثنائي',
    level: 'C1',
    partOfSpeech: 'adjective',
    definitionEn: 'Unusually good; outstanding.',
    definitionAr: 'جيد بشكل غير عادي؛ ممتاز.',
    examples: [
      'Her performance in the exam was exceptional.',
      'He is an exceptional student with remarkable abilities.',
      'The restaurant offers exceptional service and cuisine.',
    ],
    synonyms: [
      'extraordinary',
      'remarkable',
      'unparalleled',
      'outstanding',
      'superb',
    ],
    similar: [
      SimilarWord('extraordinary', 'استثنائي', 'B2'),
      SimilarWord('outstanding', 'ممتاز', 'B2'),
      SimilarWord('superb', 'رائع', 'C1'),
    ],
  ),
  'outstanding': WordEntry(
    translation: 'ممتاز / بارز',
    level: 'B2',
    partOfSpeech: 'adjective',
    definitionEn: 'Exceptionally good; extremely impressive.',
    definitionAr: 'جيد بشكل استثنائي؛ مثير للإعجاب للغاية.',
    examples: [
      'She received an award for her outstanding work.',
      'The team gave an outstanding performance last night.',
      'His outstanding contribution was recognized by everyone.',
    ],
    synonyms: [
      'excellent',
      'superb',
      'exceptional',
      'magnificent',
      'brilliant',
    ],
    similar: [
      SimilarWord('excellent', 'ممتاز', 'A2'),
      SimilarWord('superb', 'رائع', 'C1'),
      SimilarWord('magnificent', 'مهيب', 'B2'),
    ],
  ),
  'resilience': WordEntry(
    translation: 'مرونة / قدرة على التعافي',
    level: 'C1',
    partOfSpeech: 'noun',
    definitionEn: 'The ability to recover quickly from difficulties.',
    definitionAr: 'القدرة على التعافي بسرعة من الصعوبات.',
    examples: [
      'The community showed great resilience after the natural disaster.',
      'His resilience helped him overcome many challenges in life.',
      'Mental resilience is important for success.',
    ],
    synonyms: ['toughness', 'perseverance', 'adaptability', 'endurance'],
    similar: [
      SimilarWord('perseverance', 'مثابرة', 'C1'),
      SimilarWord('endurance', 'تحمل', 'B2'),
      SimilarWord('adaptability', 'قابلية التكيف', 'C1'),
    ],
  ),
  'impressive': WordEntry(
    translation: 'مثير للإعجاب',
    level: 'B1',
    partOfSpeech: 'adjective',
    definitionEn: 'Evoking admiration through size, quality, or skill.',
    definitionAr: 'يثير الإعجاب من خلال الحجم أو الجودة أو المهارة.',
    examples: [
      'The view from the top of the tower was impressive.',
      'She gave an impressive speech at the conference.',
      'The new building has an impressive modern design.',
    ],
    synonyms: [
      'striking',
      'remarkable',
      'awe-inspiring',
      'grand',
      'awe-inspiring',
    ],
    similar: [
      SimilarWord('striking', 'لافت', 'B2'),
      SimilarWord('grand', 'عظيم', 'B1'),
      SimilarWord('awe-inspiring', 'مذهل', 'C1'),
    ],
  ),
  'inspired': WordEntry(
    translation: 'ألهم',
    level: 'B1',
    partOfSpeech: 'verb',
    definitionEn:
        'Motivated or encouraged to do something creative or positive.',
    definitionAr: 'حفز أو شجع على فعل شيء إبداعي أو إيجابي.',
    examples: [
      'The speech inspired the whole audience to take action.',
      'Her story inspired many young people to pursue their dreams.',
      'The beautiful scenery inspired the artist to paint.',
    ],
    synonyms: [
      'motivated',
      'encouraged',
      'stimulated',
      'sparked',
      'galvanized',
    ],
    similar: [
      SimilarWord('motivate', 'يحفز', 'B1'),
      SimilarWord('encourage', 'يشجع', 'B1'),
      SimilarWord('stimulate', 'يحفز', 'B2'),
    ],
  ),
  'transforming': WordEntry(
    translation: 'يحول / يغير',
    level: 'B2',
    partOfSpeech: 'verb',
    definitionEn: 'Making a thorough or dramatic change in form or character.',
    definitionAr: 'إجراء تغيير جذري أو شامل في الشكل أو الطابع.',
    examples: [
      'Technology is transforming the way we communicate.',
      'The company is transforming its business model to adapt.',
      'Education is transforming lives across the world.',
    ],
    synonyms: ['changing', 'converting', 'revolutionizing', 'remodeling'],
    similar: [
      SimilarWord('convert', 'يحول', 'B1'),
      SimilarWord('revolutionize', 'يحدث ثورة', 'C1'),
      SimilarWord('remodel', 'يعيد تشكيل', 'B2'),
    ],
  ),
  'unimaginable': WordEntry(
    translation: 'لا يمكن تخيله',
    level: 'C1',
    partOfSpeech: 'adjective',
    definitionEn: 'Impossible to imagine or comprehend.',
    definitionAr: 'من المستحيل تخيله أو استيعابه.',
    examples: [
      'The scale of the problem was unimaginable.',
      'They faced unimaginable challenges during their journey.',
      'The technology has brought unimaginable changes to our lives.',
    ],
    synonyms: ['inconceivable', 'unthinkable', 'incredible', 'mind-boggling'],
    similar: [
      SimilarWord('inconceivable', 'غير قابل للتصور', 'C1'),
      SimilarWord('unthinkable', 'غير معقول', 'C1'),
      SimilarWord('incredible', 'لا يصدق', 'B1'),
    ],
  ),
  'intelligent': WordEntry(
    translation: 'ذكي',
    level: 'B1',
    partOfSpeech: 'adjective',
    definitionEn:
        'Having or showing the ability to think, learn, and understand.',
    definitionAr: 'يملك أو يُظهر القدرة على التفكير والتعلم والفهم.',
    examples: [
      'She is an intelligent student who excels in all subjects.',
      'The system uses intelligent algorithms to optimize results.',
      'He asked an intelligent question during the discussion.',
    ],
    synonyms: ['smart', 'clever', 'bright', 'sharp', 'brilliant'],
    similar: [
      SimilarWord('smart', 'ذكي', 'A2'),
      SimilarWord('clever', 'بارع', 'B1'),
      SimilarWord('brilliant', 'عبقري', 'B2'),
    ],
  ),
  'accessible': WordEntry(
    translation: 'متاح / يمكن الوصول إليه',
    level: 'B1',
    partOfSpeech: 'adjective',
    definitionEn: 'Able to be reached, entered, or used easily.',
    definitionAr: 'يمكن الوصول إليه أو استخدامه بسهولة.',
    examples: [
      'The building is accessible to wheelchair users.',
      'Online education makes learning more accessible to everyone.',
      'The information should be accessible to all citizens.',
    ],
    synonyms: ['available', 'reachable', 'approachable', 'obtainable'],
    similar: [
      SimilarWord('available', 'متاح', 'A2'),
      SimilarWord('reachable', 'يمكن الوصول', 'B1'),
      SimilarWord('approachable', 'سهل المنال', 'B2'),
    ],
  ),
  'effective': WordEntry(
    translation: 'فعال',
    level: 'B1',
    partOfSpeech: 'adjective',
    definitionEn: 'Successful in producing a desired or intended result.',
    definitionAr: 'ناجح في إنتاج النتيجة المرجوة أو المقصودة.',
    examples: [
      'The new medicine is very effective in treating the disease.',
      'We need an effective strategy to solve this problem.',
      'Her teaching methods are highly effective.',
    ],
    synonyms: ['efficient', 'productive', 'successful', 'potent', 'powerful'],
    similar: [
      SimilarWord('efficient', 'كفؤ', 'B1'),
      SimilarWord('productive', 'منتج', 'B1'),
      SimilarWord('potent', 'قوي', 'C1'),
    ],
  ),
  'embracing': WordEntry(
    translation: 'يتبنى',
    level: 'B2',
    partOfSpeech: 'verb',
    definitionEn: 'Accepting or supporting a new idea or change willingly.',
    definitionAr: 'قبول أو دعم فكرة جديدة أو تغيير عن طيب خاطر.',
    examples: [
      'Companies are embracing digital transformation to stay competitive.',
      'She embraced the new opportunity with enthusiasm.',
      'The community embraced the changes positively.',
    ],
    synonyms: ['adopting', 'welcoming', 'accepting', 'espousing'],
    similar: [
      SimilarWord('adopt', 'يتبنى', 'B1'),
      SimilarWord('welcome', 'يرحب', 'B1'),
      SimilarWord('espouse', 'يؤيد', 'C1'),
    ],
  ),
  'engaging': WordEntry(
    translation: 'جذاب / مشوق',
    level: 'B1',
    partOfSpeech: 'adjective',
    definitionEn: 'Attractive, interesting, or appealing.',
    definitionAr: 'جذاب أو ممتع أو مثير للاهتمام.',
    examples: [
      'The teacher made the lesson very engaging for students.',
      'It was an engaging story that kept me reading all night.',
      'The game provides an engaging experience for players.',
    ],
    synonyms: ['captivating', 'absorbing', 'compelling', 'fascinating'],
    similar: [
      SimilarWord('captivating', 'آسر', 'B2'),
      SimilarWord('compelling', 'مقنع', 'C1'),
      SimilarWord('fascinating', 'رائع', 'B1'),
    ],
  ),
  'potential': WordEntry(
    translation: 'إمكانات',
    level: 'B1',
    partOfSpeech: 'noun',
    definitionEn: 'Latent qualities or abilities that may be developed.',
    definitionAr: 'صفات أو قدرات كامنة يمكن تطويرها.',
    examples: [
      'She has great potential as a writer and storyteller.',
      'The technology has enormous potential to change healthcare.',
      'We need to realize the full potential of our team.',
    ],
    synonyms: ['capability', 'capacity', 'promise', 'possibility'],
    similar: [
      SimilarWord('capability', 'قدرة', 'B1'),
      SimilarWord('capacity', 'سعة', 'B2'),
      SimilarWord('promise', 'وعد', 'A2'),
    ],
  ),
  'revolutionize': WordEntry(
    translation: 'يحدث ثورة في',
    level: 'C1',
    partOfSpeech: 'verb',
    definitionEn: 'Change something fundamentally or dramatically.',
    definitionAr: 'تغيير شيء بشكل جذري أو كبير.',
    examples: [
      'The internet revolutionized communication across the globe.',
      'This invention could revolutionize the medical industry.',
      'Electric cars are revolutionizing the automotive industry.',
    ],
    synonyms: ['transform', 'overhaul', 'dramatically change', 'reshape'],
    similar: [
      SimilarWord('transform', 'يحول', 'B2'),
      SimilarWord('reshape', 'يعيد تشكيل', 'C1'),
      SimilarWord('overhaul', 'يجدد', 'C1'),
    ],
  ),
  'enormous': WordEntry(
    translation: 'ضخم',
    level: 'B2',
    partOfSpeech: 'adjective',
    definitionEn: 'Very large in size, quantity, or extent.',
    definitionAr: 'كبير جداً في الحجم أو الكمية أو المدى.',
    examples: [
      'The project requires an enormous amount of work and resources.',
      'There is an enormous difference between the two proposals.',
      'The company has made an enormous profit this year.',
    ],
    synonyms: ['huge', 'massive', 'immense', 'colossal', 'gigantic'],
    similar: [
      SimilarWord('huge', 'ضخم', 'A2'),
      SimilarWord('massive', 'هائل', 'B2'),
      SimilarWord('immense', 'شاسع', 'C1'),
    ],
  ),
  'unveiled': WordEntry(
    translation: 'كشف عن',
    level: 'B2',
    partOfSpeech: 'verb',
    definitionEn: 'Revealed or made public for the first time.',
    definitionAr: 'تم الكشف عنه أو عرضه للعامة لأول مرة.',
    examples: [
      'The company unveiled its latest product at the tech conference.',
      'The new plan was unveiled yesterday by the CEO.',
      'They unveiled a new statue in the town square.',
    ],
    synonyms: ['revealed', 'uncovered', 'launched', 'presented', 'disclosed'],
    similar: [
      SimilarWord('reveal', 'يكشف', 'B1'),
      SimilarWord('launch', 'يطلق', 'B1'),
      SimilarWord('disclose', 'يفصح', 'C1'),
    ],
  ),
  'groundbreaking': WordEntry(
    translation: 'رائد / ثوري',
    level: 'C1',
    partOfSpeech: 'adjective',
    definitionEn:
        'Innovative and pioneering in a way that creates new opportunities.',
    definitionAr: 'مبتكر ورائد بطريقة تخلق فرصاً جديدة.',
    examples: [
      'The research represents a groundbreaking discovery in physics.',
      'It was a groundbreaking achievement in medical technology.',
      'The company is known for its groundbreaking innovations.',
    ],
    synonyms: ['innovative', 'pioneering', 'revolutionary', 'trailblazing'],
    similar: [
      SimilarWord('innovative', 'مبتكر', 'B2'),
      SimilarWord('pioneering', 'رائد', 'C1'),
      SimilarWord('revolutionary', 'ثوري', 'C1'),
    ],
  ),
  'incorporates': WordEntry(
    translation: 'يدمج / يتضمن',
    level: 'B2',
    partOfSpeech: 'verb',
    definitionEn: 'Includes or contains something as part of a whole.',
    definitionAr: 'يشمل أو يحتوي على شيء كجزء من الكل.',
    examples: [
      'The new design incorporates many advanced features.',
      'The software incorporates state-of-the-art security measures.',
      'Her speech incorporated ideas from various sources.',
    ],
    synonyms: ['includes', 'integrates', 'embodies', 'combines', 'contains'],
    similar: [
      SimilarWord('include', 'يتضمن', 'A2'),
      SimilarWord('integrate', 'يدمج', 'B2'),
      SimilarWord('embody', 'يجسد', 'C1'),
    ],
  ),
  'sophisticated': WordEntry(
    translation: 'متطور',
    level: 'C1',
    partOfSpeech: 'adjective',
    definitionEn: 'Complex, advanced, and highly developed.',
    definitionAr: 'معقد ومتقدم ومطور بشكل كبير.',
    examples: [
      'The system uses sophisticated technology to process data.',
      'She has a sophisticated understanding of the financial markets.',
      'The software employs sophisticated algorithms.',
    ],
    synonyms: ['advanced', 'complex', 'refined', 'elaborate', 'intricate'],
    similar: [
      SimilarWord('advanced', 'متقدم', 'B1'),
      SimilarWord('complex', 'معقد', 'B1'),
      SimilarWord('refined', 'مكرر', 'C1'),
    ],
  ),
  'enhance': WordEntry(
    translation: 'يعزز / يحسن',
    level: 'B1',
    partOfSpeech: 'verb',
    definitionEn: 'Increase the quality, value, or effectiveness of something.',
    definitionAr: 'زيادة جودة أو قيمة أو فعالية شيء ما.',
    examples: [
      'The new features enhance the user experience significantly.',
      'Regular exercise can enhance your overall health.',
      'Good lighting can enhance the atmosphere of a room.',
    ],
    synonyms: ['improve', 'boost', 'upgrade', 'augment', 'strengthen'],
    similar: [
      SimilarWord('improve', 'يحسن', 'A2'),
      SimilarWord('boost', 'يعزز', 'B1'),
      SimilarWord('augment', 'يزيد', 'C1'),
    ],
  ),
  'praised': WordEntry(
    translation: 'أشاد بـ',
    level: 'B1',
    partOfSpeech: 'verb',
    definitionEn:
        'Expressed warm approval or admiration for someone or something.',
    definitionAr: 'أعرب عن موافقة حارة أو إعجاب بشخص أو شيء.',
    examples: [
      'Critics praised the film for its originality.',
      'The teacher praised her students for their hard work.',
      'Everyone praised his dedication to the project.',
    ],
    synonyms: ['commended', 'applauded', 'complimented', 'acclaimed', 'lauded'],
    similar: [
      SimilarWord('commend', 'يثني على', 'B2'),
      SimilarWord('applaud', 'يصفق', 'B1'),
      SimilarWord('acclaim', 'يهتف', 'C1'),
    ],
  ),
  'influence': WordEntry(
    translation: 'يؤثر على',
    level: 'B1',
    partOfSpeech: 'verb',
    definitionEn: 'The capacity to have an effect on someone or something.',
    definitionAr: 'القدرة على التأثير على شخص أو شيء.',
    examples: [
      'The speech influenced many voters during the election.',
      'Social media can influence public opinion significantly.',
      'Her parents influenced her career choice.',
    ],
    synonyms: ['affect', 'shape', 'impact', 'guide', 'sway'],
    similar: [
      SimilarWord('affect', 'يؤثر', 'B1'),
      SimilarWord('impact', 'يؤثر', 'B1'),
      SimilarWord('sway', 'يؤثر في', 'C1'),
    ],
  ),
  'reached': WordEntry(
    translation: 'توصل إلى',
    level: 'B1',
    partOfSpeech: 'verb',
    definitionEn: 'Arrived at or achieved after effort.',
    definitionAr: 'وصل إلى أو حقق بعد جهد.',
    examples: [
      'They reached an agreement after long negotiations.',
      'We finally reached our goal after months of work.',
      'The temperature reached 40 degrees today.',
    ],
    synonyms: ['achieved', 'attained', 'arrived at', 'accomplished'],
    similar: [
      SimilarWord('achieve', 'يحقق', 'B1'),
      SimilarWord('attain', 'ينال', 'C1'),
      SimilarWord('accomplish', 'ينجز', 'B2'),
    ],
  ),
  'dramatically': WordEntry(
    translation: 'بشكل كبير / ملحوظ',
    level: 'B2',
    partOfSpeech: 'adverb',
    definitionEn: 'In a way that is striking or very noticeable.',
    definitionAr: 'بطريقة لافتة أو ملحوظة جداً.',
    examples: [
      'The price of oil has dramatically increased this year.',
      'Her health improved dramatically after the treatment.',
      'The landscape changed dramatically after the storm.',
    ],
    synonyms: ['significantly', 'considerably', 'sharply', 'markedly'],
    similar: [
      SimilarWord('significantly', 'بشكل ملحوظ', 'B2'),
      SimilarWord('considerably', 'بشكل كبير', 'B2'),
      SimilarWord('markedly', 'بشكل ملحوظ', 'C1'),
    ],
  ),
  'ambitious': WordEntry(
    translation: 'طموح',
    level: 'B2',
    partOfSpeech: 'adjective',
    definitionEn: 'Requiring great effort to achieve; challenging.',
    definitionAr: 'يتطلب جهداً كبيراً لتحقيقه؛ صعب.',
    examples: [
      'The project is very ambitious but achievable.',
      'They set ambitious goals for the coming year.',
      'She is an ambitious young professional.',
    ],
    synonyms: ['challenging', 'demanding', 'aspiring', 'grand', 'lofty'],
    similar: [
      SimilarWord('challenging', 'صعب', 'B1'),
      SimilarWord('demanding', 'متطلب', 'B2'),
      SimilarWord('aspiring', 'طموح', 'C1'),
    ],
  ),
  'commits': WordEntry(
    translation: 'يلتزم',
    level: 'B2',
    partOfSpeech: 'verb',
    definitionEn: 'Dedicates or pledges to do something.',
    definitionAr: 'يكرس أو يتعهد بفعل شيء.',
    examples: [
      'The government commits to reducing pollution by 50%.',
      'She commits herself to helping others in need.',
      'The company commits to providing quality service.',
    ],
    synonyms: ['pledges', 'obligates', 'binds', 'dedicates', 'devotes'],
    similar: [
      SimilarWord('pledge', 'يتعهد', 'B2'),
      SimilarWord('dedicate', 'يكرس', 'B1'),
      SimilarWord('devote', 'يخصص', 'B2'),
    ],
  ),
  'substantial': WordEntry(
    translation: 'كبير / جوهري',
    level: 'B2',
    partOfSpeech: 'adjective',
    definitionEn: 'Of considerable importance, size, or worth.',
    definitionAr: 'ذو أهمية أو حجم أو قيمة كبيرة.',
    examples: [
      'They made substantial progress on the project.',
      'There is a substantial difference in quality.',
      'The company reported substantial growth this quarter.',
    ],
    synonyms: ['considerable', 'significant', 'sizeable', 'ample', 'sizable'],
    similar: [
      SimilarWord('considerable', 'كبير', 'B2'),
      SimilarWord('significant', 'مهم', 'B1'),
      SimilarWord('ample', 'وافر', 'C1'),
    ],
  ),
  'crucial': WordEntry(
    translation: 'حاسم',
    level: 'B2',
    partOfSpeech: 'adjective',
    definitionEn: 'Decisive or critical in determining the outcome.',
    definitionAr: 'حاسم أو مهم في تحديد النتيجة.',
    examples: [
      'This is a crucial moment in the negotiations.',
      'Education is crucial for success in life.',
      'The next goal is crucial for the team.',
    ],
    synonyms: ['critical', 'essential', 'vital', 'key', 'pivotal'],
    similar: [
      SimilarWord('critical', 'حاسم', 'B2'),
      SimilarWord('essential', 'أساسي', 'B1'),
      SimilarWord('vital', 'حيوي', 'B2'),
    ],
  ),
  'welcomed': WordEntry(
    translation: 'رحب بـ',
    level: 'B1',
    partOfSpeech: 'verb',
    definitionEn: 'Greeted or received with pleasure or approval.',
    definitionAr: 'تم استقباله بسرور أو موافقة.',
    examples: [
      'The decision was welcomed by the entire community.',
      'They welcomed the new initiative with open arms.',
      'His proposal was welcomed by the committee.',
    ],
    synonyms: ['embraced', 'accepted', 'applauded', 'greeted', 'received'],
    similar: [
      SimilarWord('embrace', 'يتبنى', 'B2'),
      SimilarWord('accept', 'يقبل', 'A2'),
      SimilarWord('greet', 'يستقبل', 'A2'),
    ],
  ),
  'emphasize': WordEntry(
    translation: 'يؤكد على',
    level: 'B2',
    partOfSpeech: 'verb',
    definitionEn: 'Give special importance or attention to something.',
    definitionAr: 'إعطاء أهمية أو اهتمام خاص لشيء ما.',
    examples: [
      'The report emphasizes the need for immediate action.',
      'She emphasized the importance of teamwork.',
      'The teacher emphasized the key points of the lesson.',
    ],
    synonyms: ['highlight', 'stress', 'underscore', 'accentuate', 'underline'],
    similar: [
      SimilarWord('highlight', 'يسلط الضوء', 'B1'),
      SimilarWord('stress', 'يشدد', 'B1'),
      SimilarWord('underline', 'يؤكد', 'B2'),
    ],
  ),
  'immediate': WordEntry(
    translation: 'فوري',
    level: 'A2',
    partOfSpeech: 'adjective',
    definitionEn: 'Occurring or done at once; without delay.',
    definitionAr: 'يحدث أو يتم في الحال؛ دون تأخير.',
    examples: [
      'The patient needs immediate medical attention.',
      'They demanded immediate action from the government.',
      'Her immediate response was to say yes.',
    ],
    synonyms: ['instant', 'prompt', 'urgent', 'swift', 'rapid'],
    similar: [
      SimilarWord('instant', 'لحظي', 'B1'),
      SimilarWord('urgent', 'عاجل', 'B1'),
      SimilarWord('prompt', 'سريع', 'B1'),
    ],
  ),
  'implementation': WordEntry(
    translation: 'تنفيذ',
    level: 'C1',
    partOfSpeech: 'noun',
    definitionEn: 'The process of putting a decision or plan into effect.',
    definitionAr: 'عملية وضع قرار أو خطة موضع التنفيذ.',
    examples: [
      'The implementation of the new system will take several months.',
      'They are responsible for the implementation of the policy.',
      'Successful implementation requires careful planning.',
    ],
    synonyms: ['execution', 'application', 'enactment', 'realization'],
    similar: [
      SimilarWord('execution', 'تنفيذ', 'B2'),
      SimilarWord('application', 'تطبيق', 'B1'),
      SimilarWord('enactment', 'سن', 'C1'),
    ],
  ),
  'unprecedented': WordEntry(
    translation: 'غير مسبوق',
    level: 'C1',
    partOfSpeech: 'adjective',
    definitionEn: 'Never done or known before; without previous example.',
    definitionAr: 'لم يسبق له مثيل؛ دون سابقة.',
    examples: [
      'The country faced unprecedented economic challenges.',
      'It was an unprecedented achievement in space exploration.',
      'The pandemic caused unprecedented disruption worldwide.',
    ],
    synonyms: [
      'unparalleled',
      'unmatched',
      'exceptional',
      'unrivalled',
      'extraordinary',
    ],
    similar: [
      SimilarWord('unparalleled', 'لا مثيل له', 'C1'),
      SimilarWord('unmatched', 'غير مسبوق', 'C1'),
      SimilarWord('exceptional', 'استثنائي', 'C1'),
    ],
  ),
  'officially': WordEntry(
    translation: 'رسمياً',
    level: 'B1',
    partOfSpeech: 'adverb',
    definitionEn: 'In a formal or authorized way.',
    definitionAr: 'بطريقة رسمية أو مصرح بها.',
    examples: [
      'The store officially opened its doors yesterday.',
      'She was officially appointed as the new manager.',
      'The agreement was officially signed last week.',
    ],
    synonyms: ['formally', 'authoritatively', 'legitimately', 'properly'],
    similar: [
      SimilarWord('formally', 'رسمياً', 'B1'),
      SimilarWord('legitimately', 'بشكل شرعي', 'C1'),
      SimilarWord('properly', 'بشكل صحيح', 'A2'),
    ],
  ),
  'showcases': WordEntry(
    translation: 'يعرض / يبرز',
    level: 'B2',
    partOfSpeech: 'verb',
    definitionEn: 'Displays or presents something to best effect.',
    definitionAr: 'يعرض أو يقدم شيئاً بأفضل صورة.',
    examples: [
      'The museum showcases works by local artists.',
      'The event showcases the latest technology innovations.',
      'Her performance showcases her remarkable talent.',
    ],
    synonyms: ['displays', 'presents', 'exhibits', 'highlights', 'features'],
    similar: [
      SimilarWord('display', 'يعرض', 'B1'),
      SimilarWord('exhibit', 'يعرض', 'B2'),
      SimilarWord('feature', 'يتميز', 'B1'),
    ],
  ),
  'highlighting': WordEntry(
    translation: 'يسلط الضوء على',
    level: 'B2',
    partOfSpeech: 'verb',
    definitionEn: 'Drawing attention to or emphasizing something.',
    definitionAr: 'جذب الانتباه إلى شيء أو التأكيد عليه.',
    examples: [
      'The report highlights the main issues facing the industry.',
      'She highlighted the most important points in her presentation.',
      'The documentary highlights the plight of endangered species.',
    ],
    synonyms: ['emphasizing', 'stressing', 'underscoring', 'spotlighting'],
    similar: [
      SimilarWord('emphasize', 'يؤكد', 'B2'),
      SimilarWord('stress', 'يشدد', 'B1'),
      SimilarWord('spotlight', 'يسلط الضوء', 'C1'),
    ],
  ),
  'contemporary': WordEntry(
    translation: 'معاصر',
    level: 'B2',
    partOfSpeech: 'adjective',
    definitionEn: 'Living or occurring in the present time; modern.',
    definitionAr: 'يعيش أو يحدث في الوقت الحاضر؛ حديث.',
    examples: [
      'The museum features contemporary art from around the world.',
      'Contemporary music is very diverse and innovative.',
      'She is an expert in contemporary literature.',
    ],
    synonyms: ['modern', 'current', 'present-day', 'up-to-date', 'latest'],
    similar: [
      SimilarWord('modern', 'حديث', 'A2'),
      SimilarWord('current', 'حالي', 'B1'),
      SimilarWord('present-day', 'معاصر', 'B2'),
    ],
  ),
  'includes': WordEntry(
    translation: 'يتضمن / يشمل',
    level: 'A2',
    partOfSpeech: 'verb',
    definitionEn: 'Contains as part of a whole.',
    definitionAr: 'يحتوي كجزء من الكل.',
    examples: [
      'The price includes breakfast and dinner.',
      'The team includes players from five different countries.',
      'The course includes both theory and practice.',
    ],
    synonyms: ['contains', 'comprises', 'encompasses', 'covers', 'embraces'],
    similar: [
      SimilarWord('contain', 'يحتوي', 'A2'),
      SimilarWord('comprise', 'يتكون من', 'B2'),
      SimilarWord('encompass', 'يشمل', 'C1'),
    ],
  ),
  'continues': WordEntry(
    translation: 'يستمر',
    level: 'A2',
    partOfSpeech: 'verb',
    definitionEn: 'Persists in an activity or process.',
    definitionAr: 'يستمر في نشاط أو عملية.',
    examples: [
      'The tradition continues to this very day.',
      'She continues to improve her skills every day.',
      'The rain continued for hours without stopping.',
    ],
    synonyms: ['persists', 'carries on', 'keeps going', 'endures'],
    similar: [
      SimilarWord('persist', 'يثابر', 'B2'),
      SimilarWord('endure', 'يتحمل', 'C1'),
      SimilarWord('proceed', 'يمضي', 'B2'),
    ],
  ),
  'vital': WordEntry(
    translation: 'حيوي / أساسي',
    level: 'B2',
    partOfSpeech: 'adjective',
    definitionEn: 'Absolutely necessary or essential.',
    definitionAr: 'ضروري للغاية أو أساسي.',
    examples: [
      'Clean water is vital for human health.',
      'Exercise is vital for maintaining good health.',
      'The role of teachers is vital in society.',
    ],
    synonyms: [
      'essential',
      'crucial',
      'critical',
      'indispensable',
      'necessary',
    ],
    similar: [
      SimilarWord('essential', 'أساسي', 'B1'),
      SimilarWord('necessary', 'ضروري', 'A2'),
      SimilarWord('indispensable', 'لا غنى عنه', 'C1'),
    ],
  ),
  'celebrating': WordEntry(
    translation: 'يحتفي بـ',
    level: 'B1',
    partOfSpeech: 'verb',
    definitionEn: 'Marking a special occasion with festivities.',
    definitionAr: 'الاحتفال بمناسبة خاصة.',
    examples: [
      'They are celebrating their wedding anniversary.',
      'The festival celebrates cultural diversity.',
      'The whole town is celebrating the victory.',
    ],
    synonyms: ['commemorating', 'honoring', 'observing', 'marking'],
    similar: [
      SimilarWord('celebrate', 'يحتفل', 'A2'),
      SimilarWord('commemorate', 'يحيي ذكرى', 'B2'),
      SimilarWord('honor', 'يكرم', 'B1'),
    ],
  ),
  'developed': WordEntry(
    translation: 'طور / ابتكر',
    level: 'B1',
    partOfSpeech: 'verb',
    definitionEn: 'Created or designed something new over time.',
    definitionAr: 'ابتكر أو صمم شيئاً جديداً مع مرور الوقت.',
    examples: [
      'The team developed a new software solution for the problem.',
      'Scientists developed a vaccine in record time.',
      'She developed her skills through years of practice.',
    ],
    synonyms: ['created', 'designed', 'devised', 'invented', 'formulated'],
    similar: [
      SimilarWord('create', 'يبدع', 'A2'),
      SimilarWord('design', 'يصمم', 'A2'),
      SimilarWord('invent', 'يخترع', 'B1'),
    ],
  ),
  'promising': WordEntry(
    translation: 'واعد',
    level: 'B1',
    partOfSpeech: 'adjective',
    definitionEn: 'Showing great potential or hope for the future.',
    definitionAr: 'يظهر إمكانات كبيرة أو أملاً للمستقبل.',
    examples: [
      'The early results of the study are very promising.',
      'She is a promising young athlete with a bright future.',
      'The new technology shows promising applications.',
    ],
    synonyms: ['encouraging', 'hopeful', 'auspicious', 'bright', 'positive'],
    similar: [
      SimilarWord('encouraging', 'مشجع', 'B1'),
      SimilarWord('hopeful', 'متفائل', 'B1'),
      SimilarWord('auspicious', 'مبشر', 'C1'),
    ],
  ),
  'significantly': WordEntry(
    translation: 'بشكل ملحوظ',
    level: 'B2',
    partOfSpeech: 'adverb',
    definitionEn: 'In a sufficiently great or important way.',
    definitionAr: 'بطريقة كبيرة أو مهمة بما فيه الكفاية.',
    examples: [
      'Profits have significantly increased this quarter.',
      'This decision will significantly affect our future.',
      'The new method is significantly more efficient.',
    ],
    synonyms: ['considerably', 'notably', 'substantially', 'markedly'],
    similar: [
      SimilarWord('considerably', 'بشكل كبير', 'B2'),
      SimilarWord('notably', 'بشكل ملحوظ', 'B2'),
      SimilarWord('substantially', 'بشكل جوهري', 'C1'),
    ],
  ),
  'innovative': WordEntry(
    translation: 'مبتكر',
    level: 'B2',
    partOfSpeech: 'adjective',
    definitionEn: 'Featuring new methods or ideas; advanced and original.',
    definitionAr: 'يتميز بأساليب أو أفكار جديدة؛ متقدم وأصلي.',
    examples: [
      'The company is known for its innovative products.',
      'She proposed an innovative solution to the problem.',
      'Innovative thinking is essential for progress.',
    ],
    synonyms: ['original', 'creative', 'inventive', 'novel', 'pioneering'],
    similar: [
      SimilarWord('creative', 'مبدع', 'B1'),
      SimilarWord('original', 'أصلي', 'B1'),
      SimilarWord('novel', 'جديد', 'B2'),
    ],
  ),
  'combines': WordEntry(
    translation: 'يجمع بين',
    level: 'B1',
    partOfSpeech: 'verb',
    definitionEn: 'Joins or mixes together to form a whole.',
    definitionAr: 'يجمع أو يخلط معاً ليشكل كلاً واحداً.',
    examples: [
      'The program combines theory with practical experience.',
      'This recipe combines flavors from around the world.',
      'Her work combines art and science beautifully.',
    ],
    synonyms: ['merges', 'unites', 'integrates', 'blends', 'fuses'],
    similar: [
      SimilarWord('merge', 'يدمج', 'B2'),
      SimilarWord('blend', 'يخلط', 'B1'),
      SimilarWord('integrate', 'يدمج', 'B2'),
    ],
  ),
  'restore': WordEntry(
    translation: 'يستعيد / يعيد',
    level: 'B1',
    partOfSpeech: 'verb',
    definitionEn: 'Bring back to a former condition or state.',
    definitionAr: 'إعادة إلى حالة أو وضع سابق.',
    examples: [
      'The surgery restored his vision completely.',
      'They worked hard to restore the old building.',
      'The new manager hopes to restore the company profitability.',
    ],
    synonyms: ['recover', 'revive', 'reinstate', 'bring back', 'renew'],
    similar: [
      SimilarWord('recover', 'يتعافى', 'B1'),
      SimilarWord('revive', 'يحيي', 'C1'),
      SimilarWord('reinstate', 'يعيد', 'C1'),
    ],
  ),
  'experiencing': WordEntry(
    translation: 'يختبر / يمر بـ',
    level: 'B1',
    partOfSpeech: 'verb',
    definitionEn: 'Going through or living through an event or feeling.',
    definitionAr: 'يمر أو يعيش حدثاً أو شعوراً.',
    examples: [
      'Patients are experiencing significant improvements.',
      'The country is experiencing rapid economic growth.',
      'She is experiencing new challenges at work.',
    ],
    synonyms: ['undergoing', 'encountering', 'facing', 'going through'],
    similar: [
      SimilarWord('undergo', 'يخضع لـ', 'B2'),
      SimilarWord('encounter', 'يواجه', 'B2'),
      SimilarWord('face', 'يواجه', 'A2'),
    ],
  ),
  'optimistic': WordEntry(
    translation: 'متفائل',
    level: 'B2',
    partOfSpeech: 'adjective',
    definitionEn: 'Hopeful and confident about the future.',
    definitionAr: 'متفائل وواثق بشأن المستقبل.',
    examples: [
      'She is optimistic about the outcome of the project.',
      'The economic outlook is optimistic for next year.',
      'Despite the challenges, he remains optimistic.',
    ],
    synonyms: ['hopeful', 'positive', 'confident', 'upbeat', 'cheerful'],
    similar: [
      SimilarWord('hopeful', 'متفائل', 'B1'),
      SimilarWord('positive', 'إيجابي', 'B1'),
      SimilarWord('confident', 'واثق', 'B1'),
    ],
  ),
  'surged': WordEntry(
    translation: 'ارتفع بشكل حاد',
    level: 'B2',
    partOfSpeech: 'verb',
    definitionEn: 'Increased suddenly and powerfully.',
    definitionAr: 'ارتفع فجأة وبقوة.',
    examples: [
      'Stock prices surged after the announcement.',
      'Demand for the product has surged in recent months.',
      'The river surged after the heavy rain.',
    ],
    synonyms: ['soared', 'jumped', 'skyrocketed', 'spiked', 'rose sharply'],
    similar: [
      SimilarWord('soar', 'يحلق', 'B2'),
      SimilarWord('skyrocket', 'يرتفع بشكل حاد', 'C1'),
      SimilarWord('spike', 'يقفز', 'C1'),
    ],
  ),
  'increasingly': WordEntry(
    translation: 'بشكل متزايد',
    level: 'B2',
    partOfSpeech: 'adverb',
    definitionEn: 'More and more; to an increasing degree.',
    definitionAr: 'أكثر فأكثر؛ بدرجة متزايدة.',
    examples: [
      'The situation is becoming increasingly complex.',
      'More people are increasingly using mobile payments.',
      'The technology is increasingly being adopted worldwide.',
    ],
    synonyms: ['progressively', 'growing', 'steadily', 'gradually'],
    similar: [
      SimilarWord('progressively', 'تدريجياً', 'B2'),
      SimilarWord('gradually', 'تدريجياً', 'B1'),
      SimilarWord('steadily', 'بثبات', 'B1'),
    ],
  ),
  'attribute': WordEntry(
    translation: 'يعزو إلى / ينسب',
    level: 'B2',
    partOfSpeech: 'verb',
    definitionEn: 'Regard something as being caused by.',
    definitionAr: 'اعتبار شيء ما ناتجاً عن شيء آخر.',
    examples: [
      'They attribute the success to hard work and dedication.',
      'The doctor attributed his recovery to the new treatment.',
      'Experts attribute the decline to several factors.',
    ],
    synonyms: ['credit', 'ascribe', 'assign', 'put down to'],
    similar: [
      SimilarWord('credit', 'ينسب', 'B2'),
      SimilarWord('ascribe', 'ينسب', 'C1'),
      SimilarWord('assign', 'يعزو', 'B2'),
    ],
  ),
  'strong': WordEntry(
    translation: 'قوي',
    level: 'A2',
    partOfSpeech: 'adjective',
    definitionEn: 'Powerful and robust in performance or effect.',
    definitionAr: 'قوي ومتين في الأداء أو التأثير.',
    examples: [
      'The company reported strong earnings this quarter.',
      'There is strong demand for the new product.',
      'She has a strong personality.',
    ],
    synonyms: ['robust', 'solid', 'powerful', 'mighty', 'sturdy'],
    similar: [
      SimilarWord('robust', 'قوي', 'B2'),
      SimilarWord('solid', 'صلب', 'B1'),
      SimilarWord('powerful', 'قوي', 'A2'),
    ],
  ),
  'favourable': WordEntry(
    translation: 'موات / مناسب',
    level: 'B2',
    partOfSpeech: 'adjective',
    definitionEn: 'Helpful, advantageous, or positive.',
    definitionAr: 'مفيد أو مناسب أو إيجابي.',
    examples: [
      'The market conditions are favourable for investment.',
      'They received a favourable response from the audience.',
      'The weather is favourable for outdoor activities.',
    ],
    synonyms: ['advantageous', 'beneficial', 'positive', 'propitious'],
    similar: [
      SimilarWord('beneficial', 'مفيد', 'B1'),
      SimilarWord('advantageous', 'مفيد', 'C1'),
      SimilarWord('propitious', 'موات', 'C1'),
    ],
  ),
  'momentum': WordEntry(
    translation: 'زخم / قوة دافعة',
    level: 'C1',
    partOfSpeech: 'noun',
    definitionEn: 'The force gained by movement or progress over time.',
    definitionAr: 'القوة المكتسبة من الحركة أو التقدم مع مرور الوقت.',
    examples: [
      'The campaign is gaining momentum every day.',
      'The business has strong momentum going into next year.',
      'The team built momentum throughout the season.',
    ],
    synonyms: ['impetus', 'drive', 'energy', 'steam', 'push'],
    similar: [
      SimilarWord('impetus', 'زخم', 'C1'),
      SimilarWord('drive', 'دافع', 'B1'),
      SimilarWord('steam', 'قوة', 'B2'),
    ],
  ),
  'continue': WordEntry(
    translation: 'يستمر',
    level: 'A2',
    partOfSpeech: 'verb',
    definitionEn: 'Persist in an activity or process.',
    definitionAr: 'الاستمرار في نشاط أو عملية.',
    examples: [
      'The trend is expected to continue for several years.',
      'She continues to lead the team with great dedication.',
      'The rain will continue throughout the weekend.',
    ],
    synonyms: ['persist', 'carry on', 'proceed', 'keep going', 'endure'],
    similar: [
      SimilarWord('persist', 'يثابر', 'B2'),
      SimilarWord('proceed', 'يمضي', 'B2'),
      SimilarWord('endure', 'يتحمل', 'C1'),
    ],
  ),
};
